### ISSUE TITLE
Atom Ordering when converting to SMILES

### ISSUE THREAD

**Issue by vsomnath** [BioinfoMachineLearning/PoseBench#10]
Hi Alex,

Thanks for the great work -- very easy to use!

I have noticed independently, for PDBBind and PoseBusters atleast, that the conversion to SMILES and loading from SMILES does not respect the atom order in the reference SDF.

Is it currently ensured in the code that the atom order in the reference SDF file (wrt which metrics are computed) matches the atom order in the prediction SDF file? I couldn't find it on a search but maybe you can help out here.

Thanks a lot!

**Comment by amorehead** [comment]
Hey, @vsomnath! Thanks for your kind words. To your question, for all four benchmark datasets, yes. Optimal permutations of atom ordering are handled by PoseBusters (which uses RDKit's [`CalcRMS()`](https://www.rdkit.org/docs/source/rdkit.Chem.rdMolAlign.html#rdkit.Chem.rdMolAlign.CalcRMS) under the hood) when we call [`bust_table()`](https://github.com/BioinfoMachineLearning/PoseBench/blob/0f87ff2a28e825bafe630bdbb77d2e4d06b020e0/posebench/analysis/inference_analysis.py#L683).

**Comment by vsomnath** [comment]
Thanks a lot!

Perfect, that makes sense, and also good to know I wasn't making any obvious mistakes with the conversion code. I will have a look at the v0.6.0 branch, and try integrating some of these also in our evals.

I will close the issue for now, thanks again!
