### ISSUE TITLE
FABind, DynamicBind, RoseTTA install error

### ISSUE THREAD

**Issue by chemgirl97** [BioinfoMachineLearning/PoseBench#2]
Thank you for your quick response and hard work. PoseBench and Casp15 ligand scoring installed well.
Also DiffDock, NeuralPLE, and AutoDock Vina installed well.
But FABind, DynamicBind, RoseTTAFold failed.

***** DynamicBind error
 subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-req-build-pt4hvue1', '-DBUILD_TEST=OFF', '-DBUILD_BENCHMARK=OFF', '-DUSE_PYTHON=ON', '-DWITH_CUDA=ON', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-req-build-pt4hvue1/build/lib.linux-x86_64-cpython-39', '-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/tmp/pip-req-build-pt4hvue1/build/lib.linux-x86_64-cpython-39', '-DCMAKE_BUILD_TYPE=RELEASE', '-DCMAKE_PREFIX_PATH=/home/jhlee/github/PoseBench/forks/DynamicBind/DynamicBind/lib/python3.9/site-packages/torch/share/cmake']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyg-lib
ERROR: Could not build wheels for pyg-lib, which is required to install pyproject.toml-based projects
failed
CondaEnvException: Pip failed

**** FABind error
 Installing pip dependencies: \ Ran pip subprocess with arguments:
['/home/jhlee/github/PoseBench/forks/FABind/FABind/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/jhlee/github/PoseBench/environments/condaenv.e_mu6a02.requirements.txt', '--exists-action=b']
Pip subprocess output:

Pip subprocess error:
ERROR: pyg_lib-0.2.0+pt112cu113-cp39-cp39-linux_x86_64.whl is not a supported wheel on this platform.
failed
CondaEnvException: Pip failed

**** RoSETTAFold-All-Atom error
Pip subprocess error:
  Running command git clone --filter=blob:none --quiet https://github.com/NVIDIA/dllogger.git /tmp/pip-req-build-hrhb71mh
  Running command git rev-parse -q --verify 'sha^0540a43971f4a8a16693a9de9de73c1072020769'
  Running command git fetch -q https://github.com/NVIDIA/dllogger.git 0540a43971f4a8a16693a9de9de73c1072020769
ERROR: Ignored the following versions that require a different python version: 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10
ERROR: Could not find a version that satisfies the requirement signalp6==6.0+h (from versions: none)
ERROR: No matching distribution found for signalp6==6.0+h
failed
CondaEnvException: Pip failed

**Comment by amorehead** [comment]
Hi, @chemgirl97. Thank you for notifying me of these errors. I can confirm them on my end. As such, I have just [pushed a commit](https://github.com/BioinfoMachineLearning/PoseBench/commit/8373e8f7eaec1c165e2b803d1e7ef1288926085c) that should fix these issues (after testing them on my end). Let me know if these resolve these above errors for you.

**Comment by amorehead** [comment]
Happy to hear this worked!

Also, keep in mind that tomorrow I will be finalizing version 0.1.0 of `PoseBench`. Included in its release (now) is the ability to (1) perform pocket-level docking e.g., with the Astex Diverse and PoseBusters Benchmark dataset and (2) perform docking with the (pocket generalization) DockGen test dataset from the recent [DiffDock-L paper](https://openreview.net/forum?id=UfBIxpTK10).

Hopefully others will find these additions valuable for future work!
