### ISSUE TITLE
Benchmarking criteria compared with AlphaFold3 protein-ligand evaluation

### ISSUE THREAD

**Issue by zqcai19** [BioinfoMachineLearning/PoseBench#8]
@amorehead Hi! Are the benchmarking criteria in PoseBench aligned with the evaluation used in AlphaFold3 for protein-ligand predictions (i.e. pocket-aligned r.m.s.d.)?

Thanks in advance for your help!

**Comment by amorehead** [comment]
Hi, @zqcai19. For the CASP15 dataset's benchmarking results, yes, this is how the evaluation is performed. For the rest of the benchmark's datasets, we calculate a protein-aligned (not just pocket-aligned) RMSD.

**Comment by amorehead** [comment]
Hi again, @zqcai19. If you have any further questions, please let me know. Otherwise, I will be closing this issue.
