### ISSUE TITLE
Predicted apo structures with AlphaFold 3 or downloaded from the AlphaFold Protein Structure Database

### ISSUE THREAD

**Issue by stan1233** [BioinfoMachineLearning/PoseBench#9]
Hi!

Thank you for sharing your work, I have a question. What's the difference between using AlphaFold 3 to predict apo structures and directly downloading structures from the [AlphaFold Protein Structure Database](https://alphafold.ebi.ac.uk/)? The latter seems to be a more computationally efficient option, but will it have a significant impact on the results?

Best,
Guangyuan

**Comment by amorehead** [comment]
Hi, @stan1233. The difference is that (to the best of my knowledge) the AlphaFold Protein Structure Database currently stores AlphaFold 2's predicted structures, not those of AlphaFold 3. In previous versions of PoseBench (when I tried using ESMFold predicted structures), I noticed a 5-10% performance improvement for most methods after switching to using AlphaFold 3's predicted apo protein structures.

**Comment by amorehead** [comment]
Hi, @stan1233. This is a good point. Based on how I read this phrase, it seems they are primarily concerning with training new machine learning models using their AF3 predicted structures, but not necessarily evaluating other machine learning models that can use any predicted structures as inputs (unless I'm mistaken).

**Comment by amorehead** [comment]
Hi again, @stan1233. If you have any further questions, please feel free to let me know. In the meantime, I will be closing this issue.
